# Generated by Django 5.2.8 on 2026-01-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0002_remove_trainerprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
