# Generated by Django 5.2.8 on 2026-01-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_workoutplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
