# Generated by Django 5.2.8 on 2026-01-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_type_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='caller_role',
            field=models.CharField(choices=[('user', 'User'), ('trainer', 'Trainer')], default='user', max_length=10),
            preserve_default=False,
        ),
    ]
