def classify_intent(question: str) -> str:
    q = question.lower()
    # 1️⃣ medical (check FIRST)
    if any(word in q for word in [
        "diabetes",
        "bp",
        "blood pressure",
        "thyroid",
        "pcos",
        "pregnant",
        "pregnancy",
        "heart",
        "cholesterol",
        "kidney",
        "liver",
        "injury",
        "pain",
        "surgery",
        "medicine",
        "doctor",
        "allergies",
        "medications",
        "chronic",
        "emergency",
        "symptoms",
        "diagnosis",
        "treatment",
        "disease",
        "health condition",
        "injuries",
        "surgeries",
        "health concerns",
        "severe symptoms",
        "urgent",
        "healthcare provider",
        "cancer",
        "asthma",
        "arthritis",
        "headache",
        "fever",
        "cough",
        "infection",
        "virus",
        "bacteria",
        "hormonal",
        "eating disorders",
    ]):
        return "medical"
    # 2️⃣ protein supplements (before nutrition)
    if any(word in q for word in [
        "protein",
        "whey",
        "isolate",
        "concentrate",
        "powder",
        "supplement",
        "bcaa",
        "creatine",
        "casein",
        "collagen",
        "hydrolysate",
        "lactose",
        "plant-based",
        "pea",
        "rice",
        "hemp",
        "soy",
        "egg white",
        "amino acids",
        "glutamine",
        "leucine",
        "pre-workout",
        "post-workout",
        "mass gainer",
    ]):
        return "protein_supplement"
    # 3️⃣ weight loss
    if any(word in q for word in [
        "weight loss",
        "lose weight",
        "reduce weight",
        "fat loss",
        "burn fat",
        "belly fat",
        "slim",
        "slimming",
        "cut",
        "dieting",
        "calorie deficit",
        "sleep",
        "stress",
        "processed foods",
        "extreme dieting",
        "metabolism",
        "keto",
        "intermittent fasting",
        "low-carb",
        "detox",
        "cleanse",
        "appetite",
        "cravings",
    ]):
        return "weight_loss"
    # 4️⃣ workout / fitness
    if any(word in q for word in [
        "gym",
        "workout",
        "exercise",
        "training",
        "cardio",
        "weights",
        "lifting",
        "run",
        "running",
        "walk",
        "walking",
        "yoga",
        "hiit",
        "strength",
        "cardiovascular",
        "mobility",
        "flexibility",
        "squats",
        "deadlifts",
        "presses",
        "rows",
        "isolation",
        "progressive overload",
        "steady-state",
        "jogging",
        "cycling",
        "interval",
        "high-intensity",
        "stretching",
        "foam rolling",
        "specificity",
        "consistency",
        "progression",
        "balance",
        "recovery",
        "rest",
        "pilates",
        "swimming",
        "crossfit",
        "endurance",
        "muscle gain",
        "bodybuilding",
    ]):
        return "workout"
    # 5️⃣ nutrition (general food)
    if any(word in q for word in [
        "diet",
        "nutrition",
        "food",
        "eat",
        "eating",
        "meal",
        "calories",
        "carbs",
        "fat",
        "vitamin",
        "minerals",
        "carbohydrates",
        "proteins",
        "fats",
        "hydration",
        "whole grains",
        "fruits",
        "vegetables",
        "sugars",
        "poultry",
        "fish",
        "eggs",
        "dairy",
        "legumes",
        "tofu",
        "nuts",
        "seeds",
        "olive oil",
        "avocados",
        "trans fats",
        "deficit",
        "surplus",
        "portion control",
        "micronutrients",
        "macronutrients",
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "balanced diet",
        "fiber",
        "antioxidants",
    ]):
        return "nutrition"
    return "general"